In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from scipy.special import expit
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('disCleaned.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   disappearance  34 non-null     object
 1   2000           34 non-null     float64
 2   2001           34 non-null     float64
 3   2002           34 non-null     float64
 4   2003           34 non-null     float64
 5   2004           34 non-null     float64
 6   2005           34 non-null     float64
 7   2006           34 non-null     float64
 8   2007           34 non-null     float64
 9   2008           34 non-null     float64
 10  2009           34 non-null     float64
 11  2010           34 non-null     float64
 12  2011           34 non-null     float64
 13  2012           34 non-null     float64
 14  2013           34 non-null     float64
 15  2014           34 non-null     float64
 16  2015           34 non-null     float64
 17  2016           34 non-null     float64
 18  2017           34 non-null     float64
 19  2018           34 non-null     float64
dtypes: float64(19), object(1)
memory usage: 5.4+ KB

In [29]:
df.describe()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
count,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000
mean,1978.263304,2055.005380,2065.774837,2132.612932,2194.215996,2153.509307,2194.003789,2219.055560,2212.674108,2167.366528,2233.255714,2229.554027,2242.030502,2305.882353,1102.911765,1127.088235,1172.558824,1195.823529,1206.431793
std,3604.792965,3743.579295,3652.693403,3865.009684,4018.306377,3925.228589,3921.956362,3970.438805,4096.299707,4048.768126,4116.853588,4161.412146,4152.272249,4350.125186,4255.621960,4369.527264,4519.653568,4667.533632,4719.410405
min,8.810502,9.084398,8.834243,10.562217,15.523023,16.278455,28.811926,15.906515,22.747117,14.123640,12.027799,15.557007,20.997838,22.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,209.635851,244.763782,244.453729,213.757411,268.026386,243.463157,245.083907,279.130479,323.372708,238.612020,310.372430,250.805028,223.632776,262.750000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,672.318176,727.717443,771.070696,721.805823,790.444509,783.307871,795.253872,808.928780,730.532068,753.015118,809.330489,830.412493,838.651628,865.500000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1862.265526,2080.388437,2044.326119,2112.472338,2205.365742,2182.304922,2094.860177,2107.659513,1591.706320,1783.978934,1953.554586,1806.969227,1797.710208,1658.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,18745.563718,19553.653807,19124.510913,20192.677643,20972.762919,20997.544039,20667.379580,21033.273104,21652.427006,21435.967112,21783.457919,22043.891384,22231.663715,23417.000000,23767.000000,24438.000000,25243.000000,26183.000000,26514.327404

In [30]:
#taking year 2000 mean

df['Index'] = 'Higher'
df.loc[df['2000']<= 1978	,'Index'] ="Lower" 
# X = df.loc[df['2000']<= 2577	,'Index'] ="Minor" #features
X = df.iloc[0:34]#features
y = df['Index']#target
print(y)

0      Lower
1      Lower
2      Lower
3      Lower
4      Lower
5      Lower
6      Lower
7      Lower
8      Lower
9     Higher
10    Higher
11     Lower
12     Lower
13     Lower
14    Higher
15     Lower
16     Lower
17     Lower
18     Lower
19     Lower
20    Higher
21     Lower
22     Lower
23     Lower
24     Lower
25    Higher
26     Lower
27    Higher
28    Higher
29     Lower
30     Lower
31     Lower
32     Lower
33    Higher
Name: Index, dtype: object

In [31]:
X=pd.get_dummies(X)

In [32]:
X

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,disappearance_ Sweden,disappearance_ United Kingdom,disappearance_Japan,disappearance_Norway,disappearance_Russian Federation,disappearance_Switzerland,disappearance_Tunisia,disappearance_USA,Index_Higher,Index_Lower
0,874.731279,1012.663974,926.026869,719.572364,995.823775,772.066135,612.470646,846.815657,907.886818,885.715848,...,0,0,0,0,0,0,0,0,0,1
1,1133.360563,884.233268,1484.300964,1579.418571,1396.235438,1158.037756,1537.413085,1103.118346,649.930516,934.292881,...,0,0,0,0,0,0,0,0,0,1
2,275.084816,350.399596,340.568697,397.314698,364.190796,430.013986,420.382519,364.189968,444.717889,409.275903,...,0,0,0,0,0,0,0,0,0,1
3,327.123995,336.767996,354.862995,375.427996,370.009547,373.753059,386.132852,386.334464,377.142185,365.637529,...,0,0,0,0,0,0,0,0,0,1
4,66.796997,52.891097,51.378797,53.095997,59.812396,69.647505,55.495666,69.284049,77.293095,75.437867,...,0,0,0,0,0,0,0,0,0,1
5,560.226396,633.050665,641.528578,622.663259,604.683146,656.466099,631.013555,678.960778,621.412751,525.168046,...,0,0,0,0,0,0,0,0,0,1
6,790.643989,868.401388,804.592385,724.039282,848.846281,794.549607,822.493661,794.284323,688.344327,676.252995,...,0,0,0,0,0,0,0,0,0,1
7,97.338603,106.902504,110.809822,114.362263,128.524104,144.660116,166.942772,101.132007,153.860003,123.493948,...,0,0,0,0,0,0,0,0,0,1
8,967.218994,947.432834,969.585892,965.893193,1034.360393,1102.240612,1046.844360,1056.902647,1114.921820,1058.406243,...,0,0,0,0,0,0,0,0,0,1
9,5402.080678,5252.819318,5525.715323,5393.679991,4929.117167,4787.358397,5277.586460,5627.754272,5151.566678,5676.749771,...,0,0,0,0,0,0,0,0,1,0
10,8769.880653,9059.328072,8497.999682,9498.598737,10444.707853,8664.507094,9150.852967,8626.681283,9534.508272,8896.933062,...,0,0,0,0,0,0,0,0,1,0
11,687.435658,547.850855,826.548754,928.562835,871.044950,870.119458,856.588776,1014.596889,978.072539,973.875511,...,0,0,0,0,0,0,0,0,0,1
12,632.937172,646.939774,637.486875,646.086922,707.890999,569.902126,598.017810,522.203158,493.978241,445.285841,...,0,0,0,0,0,0,0,0,0,1
13,83.158199,146.240391,136.115691,150.926190,224.742784,222.891794,202.660263,244.345808,115.107083,134.496255,...,0,0,0,0,0,0,0,0,0,1
14,5149.236346,5243.277043,5182.230236,5507.114437,5468.909136,5551.826815,5593.060613,5820.949054,5892.152176,5806.024594,...,0,0,0,0,0,0,0,0,1,0
15,161.794837,149.769940,144.997269,158.570157,154.993918,144.222284,180.787614,130.850156,115.138852,88.113153,...,0,0,0,0,0,0,0,0,0,1
16,173.243675,204.320129,208.313157,173.069006,197.288302,193.421278,213.423202,230.080016,203.783059,209.777159,...,0,0,0,0,0,0,0,0,0,1
17,144.159996,133.274367,172.297021,189.867786,220.698421,226.872041,233.144180,250.616490,238.828281,221.906974,...,0,0,0,0,0,0,0,0,0,1
18,8.810502,9.084398,8.834243,10.562217,15.523023,16.278455,28.811926,15.906515,22.747117,14.123640,...,0,0,0,0,0,0,0,0,0,1
19,1859.771680,1677.078290,1573.917885,1742.501889,1978.140635,1926.930968,2128.788060,2292.091067,1323.563660,897.811609,...,0,0,0,0,0,0,0,0,0,1
20,2045.587692,2222.425077,2201.128864,2242.116070,2281.107445,2267.429574,1993.076530,1554.364851,1681.087206,2001.007687,...,0,0,0,0,0,0,0,0,1,0
21,646.394092,745.496292,719.582193,657.369283,762.650314,744.236889,768.014082,768.858282,746.508482,731.085414,...,0,0,0,0,0,0,0,0,0,1
22,551.025995,632.516895,737.549006,754.993894,818.238705,857.062792,835.125611,823.573237,806.767141,774.944821,...,0,0,0,0,0,0,0,0,0,1
23,263.315742,283.714875,275.295798,285.426286,283.175655,293.236505,280.903087,356.334574,341.034929,212.745245,...,0,0,0,0,0,0,0,0,0,1
24,172.664142,182.849001,188.465514,166.598897,184.961861,181.471872,175.688432,194.958876,194.169872,198.275123,...,0,0,0,0,0,0,0,0,0,1
25,2991.363838,2795.025489,2833.036280,2740.398901,2705.412203,3007.249560,3016.648431,3198.113102,3485.475582,3351.866483,...,0,0,0,0,0,0,0,0,1,0
26,1173.089486,1251.447987,1224.352004,1178.293186,1233.506189,1169.831743,1315.035556,1244.305656,1272.454690,1132.892674,...,1,0,0,0,0,0,0,0,0,1
27,2342.282593,2214.825152,2260.740100,2235.795821,2458.495900,2680.234475,3058.788718,2823.698258,3067.431545,3220.111866,...,0,1,0,0,0,0,0,0,1,0
28,6625.659910,6935.594938,6874.694943,6769.771949,7116.979949,7127.950949,7268.186316,7282.082552,7064.685113,7130.403460,...,0,0,1,0,0,0,0,0,1,0
29,657.200694,709.938594,692.247995,683.001658,708.938371,743.416197,721.266598,771.421710,714.555655,715.239498,...,0,0,0,1,0,0,0,0,0,1
30,1863.096808,3032.098612,3451.430790,3678.976985,3076.578237,3184.757958,3220.811372,3977.437932,3632.580114,3112.871956,...,0,0,0,0,1,0,0,0,0,1
31,826.930028,816.090216,821.025878,852.429933,722.016437,1099.332449,931.889372,988.974194,1149.301690,965.544629,...,0,0,0,0,0,1,0,0,0,1
32,191.742555,231.780084,234.173039,119.661394,262.976630,189.795856,200.404146,253.395780,317.485300,288.727161,...,0,0,0,0,0,0,1,0,0,1
33,18745.563718,19553.653807,19124.510913,20192.677643,20972.762919,20997.544039,20667.379580,21033.273104,21652.427006,21435.967112,...,0,0,0,0,0,0,0,1,1,0

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=40)

In [40]:
clf_gini = DecisionTreeClassifier(criterion = "gini",
  random_state = 100,max_depth=3, min_samples_leaf=5)

clf_gini.fit(X_train, y_train)

predictions_gini = clf_gini.predict(X_test)

clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 3, min_samples_leaf = 5)

clf_entropy.fit(X_train, y_train)
predictions_entropy = clf_entropy.predict(X_test)

In [41]:
def Report(y_test, y_pred):
    print("Report : ",
    classification_report(y_test, y_pred))

In [42]:
print("Trained acc clf gini: ", accuracy_score(y_train, clf_gini.predict(X_train)))
print("Test accuracy clf gini:", accuracy_score(y_test, predictions_gini))
print("Confusion matrix train gini: ", "\n", confusion_matrix(y_train, clf_gini.predict(X_train)))
print("Confusion matrix test gini: ", "\n",confusion_matrix(y_test, predictions_gini))

print("Trained acc clf entropy: ", accuracy_score(y_train, clf_entropy.predict(X_train)))
print("Test accuracy clf entropy:", accuracy_score(y_test, predictions_entropy))
print("Confusion matrix train entropy: ", "\n", confusion_matrix(y_train, clf_entropy.predict(X_train)))
print("Confusion matrix test entropy: ", "\n",confusion_matrix(y_test, predictions_entropy))

Trained acc clf gini:  1.0
Test accuracy clf gini: 0.9090909090909091
Confusion matrix train gini:
 [[ 6  0]
 [ 0 17]]
Confusion matrix test gini:
 [[2 0]
 [1 8]]
Trained acc clf entropy:  1.0
Test accuracy clf entropy: 0.9090909090909091
Confusion matrix train entropy:
 [[ 6  0]
 [ 0 17]]
Confusion matrix test entropy:
 [[2 0]
 [1 8]]

In [43]:
from sklearn.metrics import classification_report
print("------------------------GINI-----------------------------")
print(Report(y_train, clf_gini.predict(X_train)))
print("---------------------------------------------------------")
print(Report(y_test, predictions_gini))
print("---------------------------------------------------------")
print("-----------------------ENTROPY---------------------------")
print(Report(y_train, clf_entropy.predict(X_train)))
print("---------------------------------------------------------")
print(Report(y_test, predictions_entropy))

------------------------GINI-----------------------------
Report :                precision    recall  f1-score   support

      Higher       1.00      1.00      1.00         6
       Lower       1.00      1.00      1.00        17

    accuracy                           1.00        23
   macro avg       1.00      1.00      1.00        23
weighted avg       1.00      1.00      1.00        23

None
---------------------------------------------------------
Report :                precision    recall  f1-score   support

      Higher       0.67      1.00      0.80         2
       Lower       1.00      0.89      0.94         9

    accuracy                           0.91        11
   macro avg       0.83      0.94      0.87        11
weighted avg       0.94      0.91      0.92        11

None
---------------------------------------------------------
-----------------------ENTROPY---------------------------
Report :                precision    recall  f1-score   support

      Higher       1.00      1.00      1.00         6
       Lower       1.00      1.00      1.00        17

    accuracy                           1.00        23
   macro avg       1.00      1.00      1.00        23
weighted avg       1.00      1.00      1.00        23

None
---------------------------------------------------------
Report :                precision    recall  f1-score   support

      Higher       0.67      1.00      0.80         2
       Lower       1.00      0.89      0.94         9

    accuracy                           0.91        11
   macro avg       0.83      0.94      0.87        11
weighted avg       0.94      0.91      0.92        11

None